### ISSUE TITLE
when press about the crash 

### ISSUE THREAD

**Issue by selevn-1** [Five-Prayers/five-prayers-android#53]
## Exception
* __App Language:__ العربية
* __Version:__ 2.8.3-R
* __OS:__ Linux Android 12 - 32
<details><summary><b>Exceptions</b></summary><p>
<b>Crash log </b>
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=mailto:xxxx.xxxx.xxxxxxx@xxxxx.xxx }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2117)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1762)
	at android.app.Activity.startActivityForResult(Activity.java:5428)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:728)
	at android.app.Activity.startActivityForResult(Activity.java:5386)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:709)
	at android.app.Activity.startActivity(Activity.java:5772)
	at android.app.Activity.startActivity(Activity.java:5725)
	at androidx.preference.Preference.performClick(Preference.java:1215)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</p></details>
<hr>

**Comment by HichamBI** [comment]
Hello,

Sorry, cannot reproduce this issue.
