### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by bgenc** [Five-Prayers/five-prayers-android#66]
**Describe the bug**
Nothing works anymore. I cannot.open the app, notifications are gone. Widget is no more visible. Whatever I try to do, I get a Java crash window.

**To Reproduce**
1. Just try to interact with the app, like opening it 

**Expected behavior**
I expect it to open.

**Screenshots**
![image](https://github.com/user-attachments/assets/7bd9cda3-5ff8-4fd1-9377-4be1dd430fb3)

**Smartphone (please complete the following information):**
 - Device: [Poco F5 Pro]
 - OS: Android 14
 - Browser [vivaldi]
 - Version 6.8.3388

**Comment by bgenc** [comment]
## Exception
* __App Language:__ English
* __Version:__ 2.12.0-R
* __OS:__ Linux POCO/mondrian_global/mondrian:14/UKQ1.230804.001/V816.0.6.0.UMNMIXM:user/release-keys 14 - 34
<details><summary><b>Exceptions</b></summary><p>
<b>Crash log </b>

```
java.lang.NumberFormatException: For input string: "*******"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:660)
	at com.google.gson.stream.JsonReader.nextDouble(JsonReader.java:909)
	at com.google.gson.Gson$1.read(Gson.java:319)
	at com.google.gson.Gson$1.read(Gson.java:313)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:108)
	at com.hbouzidi.fiveprayers.timings.aladhan.AladhanAPIService.getTimingsByLatLong(AladhanAPIService.java:62)
	at com.hbouzidi.fiveprayers.timings.aladhan.AladhanTimingsService.retrieveAndSaveTimings(AladhanTimingsService.java:41)
	at com.hbouzidi.fiveprayers.timings.AbstractTimingsService.lambda$getTimingsByCity$0(AbstractTimingsService.java:59)
	at com.hbouzidi.fiveprayers.timings.AbstractTimingsService.$r8$lambda$UyTUM1Adur_75B8zWkfuuzl6EWI(Unknown Source:0)
	at com.hbouzidi.fiveprayers.timings.AbstractTimingsService$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.lang.Thread.run(Thread.java:1012)

```
</p></details>
<hr>

**Comment by sidzwans** [comment]
For some reason, it tries to connect to some something through internet, may be for some service etc which is not available, not sure. As a temporary measure, if you manage to disable network connection for the app, it will work.

**Comment by bgenc** [comment]
Somehow it started working again. I didn't change anything. Weird.
